apiVersion: v1
kind: Service
metadata:
  name: delivery-service
  namespace: default
  labels:
    app: delivery-service
spec:
  type: ClusterIP
  selector:
    app: delivery-service
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
